# Generated by Django 3.1.2 on 2020-10-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=40)),
                ('userName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poemTitle', models.CharField(max_length=100)),
                ('poemWriter', models.CharField(max_length=30)),
                ('poemContent', models.TextField()),
                ('poemLikeNum', models.IntegerField()),
                ('users', models.ManyToManyField(to='poem.User')),
            ],
        ),
    ]
