# Generated by Django 3.1.2 on 2020-10-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='poemContent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='poem',
            old_name='poemLikeNum',
            new_name='likenum',
        ),
        migrations.RenameField(
            model_name='poem',
            old_name='poemTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='poem',
            old_name='poemWriter',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='name',
        ),
    ]
