# Generated by Django 3.1.2 on 2020-11-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20201101_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='user_id',
            new_name='owner',
        ),
    ]
