# Generated by Django 3.1.2 on 2020-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20201028_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='likenum',
            field=models.IntegerField(default=0),
        ),
    ]
