# Generated by Django 3.1.2 on 2020-11-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0006_auto_20201101_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='poem_n',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='poem.poem'),
        ),
    ]
