# Generated by Django 3.1.2 on 2020-11-02 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poem', '0010_auto_20201102_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('poem_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='poem.poem')),
            ],
            options={
                'unique_together': {('owner', 'poem_n')},
            },
        ),
        migrations.DeleteModel(
            name='Recommended',
        ),
    ]
