# Generated by Django 3.1.2 on 2020-11-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0011_auto_20201102_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExPoet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='poem',
            name='expoet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poem.expoet'),
        ),
        migrations.AddField(
            model_name='poem',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem.tag'),
        ),
    ]
