# Generated by Django 3.1.2 on 2020-11-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0014_feeling_tagscore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagscore',
            unique_together={('tag', 'feeling')},
        ),
    ]
