# Generated by Django 3.1.2 on 2020-11-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0015_auto_20201114_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagscore',
            name='feeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagscore', to='poem.feeling'),
        ),
        migrations.AlterField(
            model_name='tagscore',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.tag'),
        ),
    ]
