# Generated by Django 3.1.2 on 2020-11-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0018_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
