# Generated by Django 3.1.2 on 2020-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0019_auto_20201117_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
