# Generated by Django 3.1.2 on 2020-11-17 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0021_auto_20201117_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
