# Generated by Django 3.1.2 on 2020-11-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0023_auto_20201118_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagscore',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
