# Generated by Django 3.1.2 on 2020-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0024_auto_20201118_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagscore',
            name='score',
            field=models.FloatField(default=1),
        ),
    ]
