# Generated by Django 3.1.2 on 2020-12-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0025_auto_20201118_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoemTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poemtags', to='poem.poem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.tag')),
            ],
            options={
                'unique_together': {('poem', 'tag')},
            },
        ),
    ]
