# Generated by Django 3.1.2 on 2020-12-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0026_poemtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='tag',
        ),
    ]
