# Generated by Django 3.1.2 on 2020-10-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociallogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glogintoken',
            old_name='token',
            new_name='idToken',
        ),
    ]
